name: Release Version

on:
  workflow_dispatch:
    inputs:
      fileName: 
        description: 'this is user input for c++ file'
        required: true
        type: string
concurrency:  
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
 
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Install g++ compiler
      run: sudo apt-get update && sudo apt-get install -y g++
    - name: Verify g++ version
      run: g++ --version
    - name: sleep
      run: sleep 60s
    - name: Build project
      run: |
    - name: Print the input tag to STDOUT
      run: echo  The tags are ${{ inputs.fileName }} 
        g++ "${{ inputs.fileName }}"
      if: ${{success()}} 

