name: C/C++ CI

on:
  workflow_run:
    workflows: ["Release Version"]
    types:
      - completed


permissions:
  contents: write
 
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Install g++ compiler
      run: echo "Hello world"
